class AddColumnsToStatisticalCalculations < ActiveRecord::Migration[7.0]
  def change
    add_column :statistical_calculations, :u_1_percentil_99, :decimal
    add_column :statistical_calculations, :u_1_percentil_95, :decimal
    add_column :statistical_calculations, :u_1_percentil_5, :decimal
    add_column :statistical_calculations, :u_2_percentil_99, :decimal
    add_column :statistical_calculations, :u_2_percentil_95, :decimal
    add_column :statistical_calculations, :u_2_percentil_5, :decimal
    add_column :statistical_calculations, :u_3_percentil_99, :decimal
    add_column :statistical_calculations, :u_3_percentil_95, :decimal
    add_column :statistical_calculations, :u_3_percentil_5, :decimal
    add_column :statistical_calculations, :I_1_percentil_99, :decimal
    add_column :statistical_calculations, :I_1_percentil_95, :decimal
    add_column :statistical_calculations, :I_1_percentil_5, :decimal
    add_column :statistical_calculations, :I_2_percentil_99, :decimal
    add_column :statistical_calculations, :I_2_percentil_95, :decimal
    add_column :statistical_calculations, :I_2_percentil_5, :decimal
    add_column :statistical_calculations, :I_3_percentil_99, :decimal
    add_column :statistical_calculations, :I_3_percentil_95, :decimal
    add_column :statistical_calculations, :I_3_percentil_5, :decimal
    add_column :statistical_calculations, :p_fetot_cap_percentil_99, :decimal
    add_column :statistical_calculations, :p_fetot_cap_percentil_95, :decimal
    add_column :statistical_calculations, :p_fetot_cap_percentil_5, :decimal
    add_column :statistical_calculations, :p_fetot_ind_percentil_99, :decimal
    add_column :statistical_calculations, :p_fetot_ind_percentil_95, :decimal
    add_column :statistical_calculations, :p_fetot_ind_percentil_5, :decimal
    add_column :statistical_calculations, :p_fund_tot_percentil_99, :decimal
    add_column :statistical_calculations, :p_fund_tot_percentil_95, :decimal
    add_column :statistical_calculations, :p_fund_tot_percentil_5, :decimal
    add_column :statistical_calculations, :q_tot_cap_percentil_99, :decimal
    add_column :statistical_calculations, :q_tot_cap_percentil_95, :decimal
    add_column :statistical_calculations, :q_tot_cap_percentil_5, :decimal
    add_column :statistical_calculations, :q_tot_ind_percentil_99, :decimal
    add_column :statistical_calculations, :q_tot_ind_percentil_95, :decimal
    add_column :statistical_calculations, :q_tot_ind_percentil_5, :decimal
    add_column :statistical_calculations, :thd_u_1_percentil_99, :decimal
    add_column :statistical_calculations, :thd_u_1_percentil_95, :decimal
    add_column :statistical_calculations, :thd_u_1_percentil_5, :decimal
    add_column :statistical_calculations, :thd_u_2_percentil_99, :decimal
    add_column :statistical_calculations, :thd_u_2_percentil_95, :decimal
    add_column :statistical_calculations, :thd_u_2_percentil_5, :decimal
    add_column :statistical_calculations, :thd_u_3_percentil_99, :decimal
    add_column :statistical_calculations, :thd_u_3_percentil_95, :decimal
    add_column :statistical_calculations, :thd_u_3_percentil_5, :decimal
    add_column :statistical_calculations, :thd_i_1_percentil_99, :decimal
    add_column :statistical_calculations, :thd_i_1_percentil_95, :decimal
    add_column :statistical_calculations, :thd_i_1_percentil_5, :decimal
    add_column :statistical_calculations, :thd_i_2_percentil_99, :decimal
    add_column :statistical_calculations, :thd_i_2_percentil_95, :decimal
    add_column :statistical_calculations, :thd_i_2_percentil_5, :decimal
    add_column :statistical_calculations, :thd_i_3_percentil_99, :decimal
    add_column :statistical_calculations, :thd_i_3_percentil_95, :decimal
    add_column :statistical_calculations, :thd_i_3_percentil_5, :decimal
    add_column :statistical_calculations, :u_percent_percentil_99, :decimal
    add_column :statistical_calculations, :u_percent_percentil_95, :decimal
    add_column :statistical_calculations, :u_percent_percentil_5, :decimal
    add_column :statistical_calculations, :i_percent_percentil_99, :decimal
    add_column :statistical_calculations, :i_percent_percentil_95, :decimal
    add_column :statistical_calculations, :i_percent_percentil_5, :decimal
  end
end
